# Generated by Django 3.1 on 2020-09-17 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'EN PROGRESO'), ('2', 'EN ESPERA'), ('3', 'RESPONDIDA')], default='2', max_length=20)),
                ('tipo', models.CharField(choices=[('1', 'PETICION'), ('2', 'QUEJA'), ('3', 'RECLAMO')], default='1', max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('create_at', models.TimeField(default=datetime.datetime(2020, 9, 16, 22, 3, 23, 990623))),
                ('nota', models.TextField(blank=True, null=True)),
                ('response_at', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
