# Generated by Django 3.1 on 2020-09-17 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='create_at',
            field=models.TimeField(default=datetime.datetime(2020, 9, 16, 22, 3, 45, 648618)),
        ),
    ]
