# Generated by Django 3.1 on 2020-09-17 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_auto_20200916_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='create_at',
            field=models.TimeField(default=datetime.datetime(2020, 9, 16, 23, 50, 53, 158789)),
        ),
    ]
